// Code generated by protoc-gen-go. DO NOT EDIT.
// source: values.proto

package datavalues

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Value struct {
	// Types that are valid to be assigned to Value:
	//	*Value_Null
	//	*Value_Phantom
	//	*Value_Int
	//	*Value_Float
	//	*Value_Bool
	//	*Value_String_
	//	*Value_Time
	//	*Value_Duration
	//	*Value_Tuple
	//	*Value_Object
	Value                isValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{0}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

type isValue_Value interface {
	isValue_Value()
}

type Value_Null struct {
	Null bool `protobuf:"varint,1,opt,name=null,proto3,oneof"`
}

type Value_Phantom struct {
	Phantom bool `protobuf:"varint,2,opt,name=phantom,proto3,oneof"`
}

type Value_Int struct {
	Int int64 `protobuf:"varint,3,opt,name=int,proto3,oneof"`
}

type Value_Float struct {
	Float float64 `protobuf:"fixed64,4,opt,name=float,proto3,oneof"`
}

type Value_Bool struct {
	Bool bool `protobuf:"varint,5,opt,name=bool,proto3,oneof"`
}

type Value_String_ struct {
	String_ string `protobuf:"bytes,6,opt,name=string,proto3,oneof"`
}

type Value_Time struct {
	Time *timestamp.Timestamp `protobuf:"bytes,7,opt,name=time,proto3,oneof"`
}

type Value_Duration struct {
	Duration *duration.Duration `protobuf:"bytes,8,opt,name=duration,proto3,oneof"`
}

type Value_Tuple struct {
	Tuple *Tuple `protobuf:"bytes,9,opt,name=tuple,proto3,oneof"`
}

type Value_Object struct {
	Object *Object `protobuf:"bytes,10,opt,name=object,proto3,oneof"`
}

func (*Value_Null) isValue_Value() {}

func (*Value_Phantom) isValue_Value() {}

func (*Value_Int) isValue_Value() {}

func (*Value_Float) isValue_Value() {}

func (*Value_Bool) isValue_Value() {}

func (*Value_String_) isValue_Value() {}

func (*Value_Time) isValue_Value() {}

func (*Value_Duration) isValue_Value() {}

func (*Value_Tuple) isValue_Value() {}

func (*Value_Object) isValue_Value() {}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetNull() bool {
	if x, ok := m.GetValue().(*Value_Null); ok {
		return x.Null
	}
	return false
}

func (m *Value) GetPhantom() bool {
	if x, ok := m.GetValue().(*Value_Phantom); ok {
		return x.Phantom
	}
	return false
}

func (m *Value) GetInt() int64 {
	if x, ok := m.GetValue().(*Value_Int); ok {
		return x.Int
	}
	return 0
}

func (m *Value) GetFloat() float64 {
	if x, ok := m.GetValue().(*Value_Float); ok {
		return x.Float
	}
	return 0
}

func (m *Value) GetBool() bool {
	if x, ok := m.GetValue().(*Value_Bool); ok {
		return x.Bool
	}
	return false
}

func (m *Value) GetString_() string {
	if x, ok := m.GetValue().(*Value_String_); ok {
		return x.String_
	}
	return ""
}

func (m *Value) GetTime() *timestamp.Timestamp {
	if x, ok := m.GetValue().(*Value_Time); ok {
		return x.Time
	}
	return nil
}

func (m *Value) GetDuration() *duration.Duration {
	if x, ok := m.GetValue().(*Value_Duration); ok {
		return x.Duration
	}
	return nil
}

func (m *Value) GetTuple() *Tuple {
	if x, ok := m.GetValue().(*Value_Tuple); ok {
		return x.Tuple
	}
	return nil
}

func (m *Value) GetObject() *Object {
	if x, ok := m.GetValue().(*Value_Object); ok {
		return x.Object
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Value) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Value_Null)(nil),
		(*Value_Phantom)(nil),
		(*Value_Int)(nil),
		(*Value_Float)(nil),
		(*Value_Bool)(nil),
		(*Value_String_)(nil),
		(*Value_Time)(nil),
		(*Value_Duration)(nil),
		(*Value_Tuple)(nil),
		(*Value_Object)(nil),
	}
}

type Tuple struct {
	Fields               []*Value `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tuple) Reset()         { *m = Tuple{} }
func (m *Tuple) String() string { return proto.CompactTextString(m) }
func (*Tuple) ProtoMessage()    {}
func (*Tuple) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{1}
}

func (m *Tuple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tuple.Unmarshal(m, b)
}
func (m *Tuple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tuple.Marshal(b, m, deterministic)
}
func (m *Tuple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tuple.Merge(m, src)
}
func (m *Tuple) XXX_Size() int {
	return xxx_messageInfo_Tuple.Size(m)
}
func (m *Tuple) XXX_DiscardUnknown() {
	xxx_messageInfo_Tuple.DiscardUnknown(m)
}

var xxx_messageInfo_Tuple proto.InternalMessageInfo

func (m *Tuple) GetFields() []*Value {
	if m != nil {
		return m.Fields
	}
	return nil
}

type Object struct {
	Fields               map[string]*Value `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{2}
}

func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetFields() map[string]*Value {
	if m != nil {
		return m.Fields
	}
	return nil
}

func init() {
	proto.RegisterType((*Value)(nil), "datatypes.Value")
	proto.RegisterType((*Tuple)(nil), "datatypes.Tuple")
	proto.RegisterType((*Object)(nil), "datatypes.Object")
	proto.RegisterMapType((map[string]*Value)(nil), "datatypes.Object.FieldsEntry")
}

func init() { proto.RegisterFile("values.proto", fileDescriptor_5d19e76c3b90e014) }

var fileDescriptor_5d19e76c3b90e014 = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x5f, 0x4b, 0xf3, 0x30,
	0x14, 0xc6, 0x9b, 0x75, 0xed, 0xd6, 0xb3, 0xf7, 0x62, 0xef, 0xe1, 0xe5, 0x25, 0x16, 0xd4, 0xb2,
	0x0b, 0x29, 0x08, 0x9d, 0x7f, 0x10, 0xc5, 0x4b, 0x51, 0x29, 0x78, 0x21, 0x94, 0xe1, 0x7d, 0xeb,
	0xb2, 0x59, 0xcd, 0x9a, 0xd2, 0xa6, 0xc2, 0xbe, 0x83, 0x1f, 0xd2, 0x8f, 0x22, 0x49, 0xda, 0x31,
	0x36, 0xef, 0x72, 0xce, 0xf3, 0x3b, 0x4f, 0xf2, 0xe4, 0xc0, 0x9f, 0xcf, 0x94, 0x37, 0xac, 0x8e,
	0xca, 0x4a, 0x48, 0x81, 0xde, 0x3c, 0x95, 0xa9, 0x5c, 0x97, 0xac, 0xf6, 0x8f, 0x97, 0x42, 0x2c,
	0x39, 0x9b, 0x6a, 0x21, 0x6b, 0x16, 0x53, 0x99, 0xaf, 0x58, 0x2d, 0xd3, 0x55, 0x69, 0x58, 0xff,
	0x68, 0x17, 0x98, 0x37, 0x55, 0x2a, 0x73, 0x51, 0x18, 0x7d, 0xf2, 0xdd, 0x03, 0xe7, 0x45, 0x99,
	0xe3, 0x3f, 0xe8, 0x17, 0x0d, 0xe7, 0x94, 0x04, 0x24, 0x1c, 0xc6, 0x56, 0xa2, 0x2b, 0xf4, 0x61,
	0x50, 0xbe, 0xa5, 0x85, 0x14, 0x2b, 0xda, 0x6b, 0x85, 0xae, 0x81, 0x08, 0x76, 0x5e, 0x48, 0x6a,
	0x07, 0x24, 0xb4, 0x63, 0x2b, 0x51, 0x05, 0xfe, 0x07, 0x67, 0xc1, 0x45, 0x2a, 0x69, 0x3f, 0x20,
	0x21, 0x89, 0xad, 0xc4, 0x94, 0xca, 0x3d, 0x13, 0x82, 0x53, 0xa7, 0x73, 0x57, 0x15, 0x52, 0x70,
	0x6b, 0x59, 0xe5, 0xc5, 0x92, 0xba, 0x01, 0x09, 0xbd, 0xd8, 0x4a, 0xda, 0x1a, 0xcf, 0xa0, 0xaf,
	0xa2, 0xd0, 0x41, 0x40, 0xc2, 0xd1, 0x85, 0x1f, 0x99, 0x18, 0x51, 0x17, 0x23, 0x9a, 0x75, 0x39,
	0x95, 0x97, 0x22, 0xf1, 0x1a, 0x86, 0x5d, 0x36, 0x3a, 0xd4, 0x53, 0x07, 0x7b, 0x53, 0xf7, 0x2d,
	0x10, 0x5b, 0xc9, 0x06, 0xc6, 0x10, 0x1c, 0xd9, 0x94, 0x9c, 0x51, 0x4f, 0x4f, 0x8d, 0xa3, 0xcd,
	0xf7, 0x46, 0x33, 0xd5, 0x57, 0x21, 0x34, 0x80, 0xa7, 0xe0, 0x8a, 0xec, 0x9d, 0xbd, 0x4a, 0x0a,
	0x1a, 0xfd, 0xbb, 0x85, 0x3e, 0x6b, 0x41, 0x25, 0x30, 0xc8, 0xdd, 0x00, 0x1c, 0xbd, 0xb5, 0xc9,
	0x39, 0x38, 0xda, 0x07, 0x43, 0x70, 0x17, 0x39, 0xe3, 0xf3, 0x9a, 0x92, 0xc0, 0xde, 0xb9, 0x49,
	0xef, 0x20, 0x69, 0xf5, 0xc9, 0x17, 0x01, 0xd7, 0x18, 0xe2, 0xd5, 0xce, 0xd0, 0xe1, 0xde, 0x9d,
	0xd1, 0xa3, 0xd6, 0x1f, 0x0a, 0x59, 0xad, 0x3b, 0x07, 0xff, 0x09, 0x46, 0x5b, 0x6d, 0x1c, 0x83,
	0xfd, 0xc1, 0xd6, 0x7a, 0xb7, 0x5e, 0xa2, 0x8e, 0x78, 0xd2, 0x3e, 0x4f, 0xaf, 0xf5, 0xb7, 0xb7,
	0x18, 0xf9, 0xb6, 0x77, 0x43, 0x32, 0x57, 0x7f, 0xe0, 0xe5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xb5, 0x0b, 0xc0, 0xf9, 0x87, 0x02, 0x00, 0x00,
}
